version:             "2"
networks:
  app-tier:
    driver:          bridge
services:
  web-monitoring:
    build:           .
    ports:
      - "1603:1603"
    depends_on:
      - mongo
    networks:
      - app-tier
  mongo:
    image:           mongo
    ports:
      - "27017:27017"
    networks:
      - app-tier
  kafka:
    image:           spotify/kafka:latest
    ports:
      - "2181:2181"
      - "9092:9092"
    hostname:        kafka
    container_name:  kafka
    environment:
      - "ADVERTISED_HOST=kafka"
      - "ADVERTISED_PORT=9092"
      - "AUTO_CREATE_TOPICS=true"
    networks:
      - app-tier
  prometheus:
      build:         prom/prometheus:0.18.0
       volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - '-config.file=/etc/prometheus/prometheus.yml'
        ports:
            - '9090:9090'
      networks:
        - app-tier
  node-exporter:
      image:         prom/node-exporter:0.12
      networks:
        - app-tier
  grafana:
      image:         grafana/grafana:latest
      environment:
          - GF_SECURITY_ADMIN_PASSWORD=pass
      volumes:
          - grafana_data:/var/lib/grafana
      depends_on:
          - prometheus
      networks:
        - app-tier
volumes:
    grafana_data:    {}
