version: "2"
networks:
  app-tier:
    driver: bridge
services:
  web-monitoring:
    build: .
    ports:
      - "1603:1603"
    depends_on:
      - mongo
    networks:
      - app-tier
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-tier
  kafka:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    hostname: kafka
    container_name: kafka
    environment:
      - "ADVERTISED_HOST=kafka"
      - "ADVERTISED_PORT=9092"
      - "AUTO_CREATE_TOPICS=true"
    networks:
      - app-tier
