version: "2"
networks:
  app-tier:
    driver: bridge
services:
  web-monitoring:
    build: .
    ports:
      - "1603:1603"
    depends_on:
      - mongo
      - zookeeper
      - kafka
    networks:
      - app-tier
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-tier
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-tier
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - app-tier
